// swift-tools-version: 5.9
//
// Generated by Scripts/render-package.sh for core-v2026.09.14.

import Foundation
import PackageDescription

let useLocalCore = ProcessInfo.processInfo.environment["MIHOME_LOCAL_CORE"] == "1"

let coreTarget: Target = useLocalCore
    ? .binaryTarget(
        name: "MihomeCore",
        path: "MihomeCore.xcframework"
    )
    : .binaryTarget(
        name: "MihomeCore",
        url: "https://github.com/decemlabs/mihome-proxy/releases/download/core-v2026.09.14/MihomeCore-core-v2026.09.14.xcframework.zip",
        checksum: "8ad2f245af6167fcb9772284f460e33ae960f0c10693a033128e291a774ff7de"
    )

let package = Package(
    name: "MihomeCore",
    platforms: [
        .iOS(.v15),
    ],
    products: [
        .library(name: "MihomeCore", targets: ["MihomeCore"]),
    ],
    targets: [coreTarget]
)
