// swift-tools-version: 5.9
//
// Generated by Scripts/render-package.sh for core-v2026.08.17.

import Foundation
import PackageDescription

let useLocalCore = ProcessInfo.processInfo.environment["MIHOME_LOCAL_CORE"] == "1"

let coreTarget: Target = useLocalCore
    ? .binaryTarget(
        name: "MihomeCore",
        path: "MihomeCore.xcframework"
    )
    : .binaryTarget(
        name: "MihomeCore",
        url: "https://github.com/decemlabs/mihome-proxy/releases/download/core-v2026.08.17/MihomeCore-core-v2026.08.17.xcframework.zip",
        checksum: "0510a00ea4b4e1dcbd1b4e0679b0c25466da70f5f320eae240281f011078af13"
    )

let package = Package(
    name: "MihomeCore",
    platforms: [
        .iOS(.v15),
    ],
    products: [
        .library(name: "MihomeCore", targets: ["MihomeCore"]),
    ],
    targets: [coreTarget]
)
