// swift-tools-version: 5.9
//
// Generated by Scripts/render-package.sh for core-v2026.10.01.

import Foundation
import PackageDescription

let useLocalCore = ProcessInfo.processInfo.environment["MIHOME_LOCAL_CORE"] == "1"

let coreTarget: Target = useLocalCore
    ? .binaryTarget(
        name: "MihomeCore",
        path: "MihomeCore.xcframework"
    )
    : .binaryTarget(
        name: "MihomeCore",
        url: "https://github.com/decemlabs/mihome-proxy/releases/download/core-v2026.10.01/MihomeCore-core-v2026.10.01.xcframework.zip",
        checksum: "f76522c3ec24925c4bae09191acd83bb10647c9b2b65ca59827e9e0b82d29c5e"
    )

let package = Package(
    name: "MihomeCore",
    platforms: [
        .iOS(.v15),
    ],
    products: [
        .library(name: "MihomeCore", targets: ["MihomeCore"]),
    ],
    targets: [coreTarget]
)
