#!/usr/bin/env bash

set -euo pipefail

if [[ "$#" -ne 2 ]]; then
    echo "usage: $0 <core-tag> <swiftpm-checksum>" >&2
    exit 2
fi

TAG="$1"
CHECKSUM="$2"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PACKAGE_FILE="$ROOT/Package.swift"

if [[ ! "$TAG" =~ ^core-v[0-9]{4}\.[0-9]{2}\.[0-9]{2}(\.[0-9]+)?$ ]]; then
    echo "error: invalid core tag: $TAG" >&2
    exit 2
fi
if [[ ! "$CHECKSUM" =~ ^[0-9a-f]{64}$ ]]; then
    echo "error: checksum must be 64 lowercase hexadecimal characters" >&2
    exit 2
fi

cat > "$PACKAGE_FILE" <<EOF
// swift-tools-version: 5.9
//
// Generated by Scripts/render-package.sh for $TAG.

import Foundation
import PackageDescription

let useLocalCore = ProcessInfo.processInfo.environment["MIHOME_LOCAL_CORE"] == "1"

let coreTarget: Target = useLocalCore
    ? .binaryTarget(
        name: "EverywhereCore",
        path: "EverywhereCore.xcframework"
    )
    : .binaryTarget(
        name: "EverywhereCore",
        url: "https://github.com/decemlabs/mihome-proxy/releases/download/$TAG/EverywhereCore-$TAG.xcframework.zip",
        checksum: "$CHECKSUM"
    )

let package = Package(
    name: "EverywhereCore",
    platforms: [
        .iOS(.v15),
    ],
    products: [
        .library(name: "EverywhereCore", targets: ["EverywhereCore"]),
    ],
    targets: [coreTarget]
)
EOF

echo "✓ wrote $PACKAGE_FILE for $TAG"
