// swift-tools-version: 5.9
//
// Generated by Scripts/render-package.sh for core-v2026.07.28.

import Foundation
import PackageDescription

let useLocalCore = ProcessInfo.processInfo.environment["MIHOME_LOCAL_CORE"] == "1"

let coreTarget: Target = useLocalCore
    ? .binaryTarget(
        name: "EverywhereCore",
        path: "EverywhereCore.xcframework"
    )
    : .binaryTarget(
        name: "EverywhereCore",
        url: "https://github.com/decemlabs/mihome-proxy/releases/download/core-v2026.07.28/EverywhereCore-core-v2026.07.28.xcframework.zip",
        checksum: "2e87e16f72f81f11dcf792ddd95124d3f8b393118cc88c8dd9196e513e333c82"
    )

let package = Package(
    name: "EverywhereCore",
    platforms: [
        .iOS(.v15),
    ],
    products: [
        .library(name: "EverywhereCore", targets: ["EverywhereCore"]),
    ],
    targets: [coreTarget]
)
