// swift-tools-version: 5.9
//
// Generated by Scripts/render-package.sh for core-v2026.07.28.1.

import Foundation
import PackageDescription

let useLocalCore = ProcessInfo.processInfo.environment["MIHOME_LOCAL_CORE"] == "1"

let coreTarget: Target = useLocalCore
    ? .binaryTarget(
        name: "MihomeCore",
        path: "MihomeCore.xcframework"
    )
    : .binaryTarget(
        name: "MihomeCore",
        url: "https://github.com/decemlabs/mihome-proxy/releases/download/core-v2026.07.28.1/MihomeCore-core-v2026.07.28.1.xcframework.zip",
        checksum: "d29281ca6d43306097db63d2374983fb8d1b1be699baa4092238ac42e1000e6c"
    )

let package = Package(
    name: "MihomeCore",
    platforms: [
        .iOS(.v15),
    ],
    products: [
        .library(name: "MihomeCore", targets: ["MihomeCore"]),
    ],
    targets: [coreTarget]
)
